[features]
seeds = false

[programs.devnet]
rust_program = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/yashpatel/.config/solana/id.json"

[scripts]
test = "yarn run mocha -t 1000000 tests/"
